---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podservices.homelabz.com.br
spec:
  group: homelabz.com.br
  names:
    kind: PodService
    listKind: PodServiceList
    plural: podservices
    singular: podservice
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              port:
                type: integer
              cpuLimit:
                type: string
              memLimit:
                type: string
              cpuReq:
                type: string
              memReq:
                type: string
            required:
            - image
    subresources:
      status: {}
