---
version: "3"

tasks:
  init:
    desc: Initialize Kubernetes addons for the Kind cluster
    preconditions:
      - sh: kind get clusters | grep -i {{.KIND_CLUSTER_NAME}}
        msg: 'echo "kind cluster ({{.KIND_CLUSTER_NAME}}) does not exist. to fix run `task kind:create`"'
    cmds:
      - task: ingress-nginx
      - task: metacontroller

  ingress-nginx:
    desc: Install the Ingress Nginx controller
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      - |
        kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=90s
      - kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml

  metacontroller:
    desc: Install the Metacontroller
    cmds:
      - kubectl apply -f https://github.com/metacontroller/metacontroller/releases/latest/download/metacontroller.yaml
      - |
        kubectl wait --namespace metacontroller \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/name=metacontroller \
          --timeout=90s
