---
apiVersion: homelabz.com.br/v1
kind: PodService
metadata:
  name: nginx
  namespace: pocs-kubernetes-metacontroller
spec:
  image: nginx:stable-alpine
  port: 80
  cpuReq: 50m
  cpuLimit: 100m
  memReq: 64Mi
  memLimit: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: pocs-kubernetes-metacontroller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: podservice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
